### ISSUE TITLE
安装了没有效果

### ISSUE THREAD

**Issue by mengxuntianya** [crud-boy/Youtube-Automatic-Translation#1]
在列表中成功安装后，没有效果，又把这里的代码复制过去保存，没有自动翻译成中文，只是字幕按钮被按下了，英文的就显示翻译的英文字幕，日文的就显示翻译的日文字幕。没有自动翻译成中文。

**Comment by crud-boy** [comment]
这个是根据中文关键字的，你自己改一下关键字就好了

**Comment by crud-boy** [comment]
问题修复了

**Comment by mengxuntianya** [comment]
系统：windows 10专业版，chrome版本 74.0.3729.131（64 位），更新了版本，不行，刚刚又卸载重新安装了5月4号的版本，广告还有，还是不能翻译，不知道是哪的问题。

**Comment by crud-boy** [comment]
你截图设置，我看看

**Comment by crud-boy** [comment]
按f12看看有没有错误信息

**Comment by crud-boy** [comment]
你看看tampermonkey上面是不是有几行黄色得小字，那个是权限没有打开

**Comment by mengxuntianya** [comment]
大侠可以了，是这个tampermonkey没有启用，我刚安装，不大会用，发现真的是tampermonkey被禁用了，打开就可以了，抱歉，给你添麻烦了，感谢。
