### ISSUE TITLE
能否加入中文(台湾)字幕？

### ISSUE THREAD

**Issue by galaxygh** [crud-boy/Youtube-Automatic-Translation#3]
感谢crud大佬的脚本，提升了观看非中文视频的体验。
我发现，有不少视频没有简体字幕，有中文(台湾)字幕，能否让其显示且优先性在英文翻译字幕之上？因为都能看懂且避免了机翻的生硬问题
谢谢大佬

**Comment by crud-boy** [comment]
加了，github不常更新，太麻烦，主要在下面这个链接更新
https://greasyfork.org/zh-CN/scripts/382426-youtube%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95/code
